#! /bin/bash

CLUSTER=$1
SOURCEDIR=$2
OUTPUTBASE=$3
POWHEG_PROCESS=$4
POWHEG_VERSION=$5
POWHEG_INPUT=$6
MINSLOT=$7
MINPDF=$8
MAXPDF=$9
MINID=${10}

source $SOURCEDIR/powheg_env.sh $CLUSTER $POWHEG_VERSION

RUNSLOT=
let "RUNSLOT=SLOT+MINSLOT"
export PYTHONPATH=$PYTHONPATH:$SOURCEDIR
cmd=$(printf "%s/powheg_runner.py %s %s --slot %s -t %s --minpdf %s --maxpdf %s --minid %s" $SOURCEDIR $OUTPUTBASE $POWHEG_INPUT $RUNSLOT $POWHEG_PROCESS $MINPDF $MAXPDF $MINID)
echo "Running: $cmd"
eval $cmd